### ISSUE TITLE
Enhancement: - There is no startup templates for Raising the issues on the github.

### ISSUE THREAD

**Issue by SohamTilekar** [python-ffmpegio/python-ffmpegio#28]
When we Try to Report the Issues It will Give the blank template. Issue for the pull request: - #27

Now when we try opening the issue it will give us some Templates to start the issues form.
![300285743-a6545a22-a788-461d-bc5c-6dfcc6f61baf](https://github.com/python-ffmpegio/python-ffmpegio/assets/152298897/7c73ce93-f873-47b7-9cdc-57a47bdb4929)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
![300285791-b3873041-8182-4afa-98c1-aeb58a457eb5](https://github.com/python-ffmpegio/python-ffmpegio/assets/152298897/2e034199-7ea1-4c85-aa0b-5be9e4aff10d)
! NO Templates

Templates look like the below: -
Images are taken from the other repo. Can't Take from the forked repo and main ustil pull request is Merged.
![300285614-fe499210-9da2-4576-82be-3057d6b37489](https://github.com/python-ffmpegio/python-ffmpegio/assets/152298897/603b144f-5955-46f8-8338-3a1c6fb11e29)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
Options to choose templates.
![300285254-4ff4d045-9366-4d9a-88b7-f48a6a60afce](https://github.com/python-ffmpegio/python-ffmpegio/assets/152298897/99805408-4403-43c1-ba07-598f62faebd1)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
Premade Template to start.
![300285501-eba71bf7-3a52-4fd1-ace3-dcb296099dac](https://github.com/python-ffmpegio/python-ffmpegio/assets/152298897/c51d75ee-1d31-46df-ab9f-37fb684af1a6)

**Comment by tikuma-lsuhsc** [comment]
Please limit the issue reporting to actual software issues.
