### ISSUE TITLE
subprocess.run fails when manually running equivalent command works. Possible bug in ffmpeg_args processing.

### ISSUE THREAD

**Issue by jason-dour-e** [python-ffmpegio/python-ffmpegio#30]
I'm running into a strange behavior with ffmpegio.  I've possibly traced the error down to `ffmpeg_args` processing.  Possibly in: https://github.com/python-ffmpegio/python-ffmpegio/blob/d577238d629cc0858d4617622ee3a23d6e967b04/src/ffmpegio/utils/parser.py#L145

I have the following code (variables manually built in this code example, variables in my script):
``` pyton
ffm.ffmpegprocess.run(
    ffmpeg_args = {
        "inputs": [('001.png', {'t': 9.92, 'loop': 1}), ('001.mp3', None), ('002.png', {'t': 6.608, 'loop': 1}), ('002.mp3', None), ('003.png', {'t': 31.04, 'loop': 1}), ('003.mp3', None), ('004.png', {'t': 7.472, 'loop': 1}), ('004.mp3', None), ('005.png', {'t': 5.264, 'loop': 1}), ('005.mp3', None), ('test.vtt', None)],
        "outputs": [('test.mp4', {'map': ['[vout]', '[aout]', '10:0'], 'c:v': 'libx264', 'c:a': 'aac', 'b:a': '192k', 'pix_fmt': 'yuv420p', 'tune': 'stillimage', 'c:s': 'mov_text', 'metadata:s:s:0': 'language=eng', 'movflags': '+faststart'})],
        "global_options": {
            "filter_complex": filter,
        }
    },
    overwrite = True
)
```

I have a print statement to debug my variables, and my outputs (which seem to be the issue) are:
```
outputs: [('test.mp4', {'map': ['[vout]', '[aout]', '10:0'], 'c:v': 'libx264', 'c:a': 'aac', 'b:a': '192k', 'pix_fmt': 'yuv420p', 'tune': 'stillimage', 'c:s': 'mov_text', 'metadata:s:s:0': 'language=eng', 'movflags': '+faststart'})]
```

Additionally, I've enabled debugging with `logging.basicConfig(level = logging.DEBUG)`.  Which gives me the following output:
```
-nostdin -hide_banner -y -t 9.92 -loop 1 -i 001.png -i 001.mp3 -t 6.608 -loop 1 -i 002.png -i 002.mp3 -t 31.04 -loop 1 -i 003.png -i 003.mp3 -t 7.472 -loop 1 -i 004.png -i 004.mp3 -t 5.264 -loop 1 -i 005.png -i 005.mp3 -i test.vtt -map '[vout]' -map '[aout]' -map 10:0 -c:v libx264 -c:a aac -b:a 192k -pix_fmt yuv420p -tune stillimage -tune:s mov_text -metadata:s:s:0 language=eng -movflags +faststart test.mp4
```

Note that after `-tune still image`, my `-c:s mov_text` for subtitle codec is now `-tune:s mov_text`! 

This appears to be the source of my ffmpeg run errors where it is not finding a codec defined and errors out.  When I build an `ffmpeg` command line using all of the above inputs, outputs, filter, et cetera, it works properly and encodes the video with my subtitles.

I'm not 100% certain as I'm still debugging and seeing if I can track down where this is happening, but my gut makes me think it is this:
https://github.com/python-ffmpegio/python-ffmpegio/blob/d577238d629cc0858d4617622ee3a23d6e967b04/src/ffmpegio/utils/parser.py#L145-L154

I could be wrong.  The problem may be elsewhere.  But figured I'd submit the issue and continue to trace down the bug.

Happy to provide more information as needed.  Tried to show above how the error is exhibiting.

**Comment by tikuma-lsuhsc** [comment]
@jason-dour-e - Thanks for finding this bug. You're pretty close on your analysis but the culprit is in the caller of `finalize_output`, `opts2args` to be exact. 

I'll try to push the patch this evening but in case I couldn't, here is the fix:

Line 170 of `utils/parser.py` currently reads as:

```python
if oname not in opts_parsed:
```

This line should read:

```
o = opts_parsed.get(oname,None)
if oname not in opts_parsed:
```

As an immediate workaround, you can modify the file in your python package folder as outlined above. The file is in `<venv_dir>/Lib/site_packages/ffmpegio/utils/parser.py` where `<venv_dir>` is your virtual environment folder or wherever your Python stores the package files.

Let me know if this fix doesn't fully address your issue.

**Comment by jason-dour-e** [comment]
Wow!  What a fast find and response!  Thank you!  👍

**Comment by jason-dour-e** [comment]
Just made the change locally and confirmed it fixed the issue.  Thanks!

**Comment by tikuma-lsuhsc** [comment]
👍
