### ISSUE TITLE
read() function doc error at Stream Read/Write section

### ISSUE THREAD

**Issue by se7enXF** [python-ffmpegio/python-ffmpegio#33]
* ffmpegio version: 0.9.1

In [quickstart doc](https://python-ffmpegio.github.io/python-ffmpegio/quick.html) `Stream Read/Write` section:

```python
with ffmpegio.open('mytestvideo.mp4', 'v') as f: # opens the first video stream
    print(f.frame_rate) # frame rate fraction in frames/second
    F = f.read() # read the first frame # todo Wrong here, f.read() read all frames
    F = f.read(5) # read the next 5 frames at once
```

And in ffmpegio/__init__.py, in function `open()`'s doc, line 129:

```python
with ffmpegio.open('video_source.mp4') as f:
    frame = f.read()  # here, read all frames

```

Maybe there are other errors.

**Comment by SohamTilekar** [comment]
What is the error.

**Comment by tikuma-lsuhsc** [comment]
@se7enXF - Thanks for the report. These examples (using 'r' as the default streaming mode) were originally valid but currently disabled (and I forgot to update the doc). I'll make the decision before the next release.

**Comment by tikuma-lsuhsc** [comment]
@SohamTilekar - Please refrain from responding to others' Issues threads, unless you've also encountered and are reporting the same issue, or I need others' input. You're neither the maintainer nor a contributor. Feel free, however, to be involved on Discussions threads. Thanks.

**Comment by tikuma-lsuhsc** [comment]
I've decided to require the `mode` argument so it is explicitly set every time. These documentation errors have been corrected on the main branch.
