### ISSUE TITLE
Incorrect return Type Hints for `ffmpegio.probe.video_streams_basic()` method.

### ISSUE THREAD

**Issue by JadeJuno** [python-ffmpegio/python-ffmpegio#48]
For some reason, the method [`ffmpegio.probe.video_streams_basic()`](https://github.com/python-ffmpegio/python-ffmpegio/blob/ff274d647b8a64719f60302f53cb021d2d88c1f1/src/ffmpegio/probe.py#L443-L557) has the return type hint [`dict[str, str | Number | Fraction]`](https://github.com/python-ffmpegio/python-ffmpegio/blob/ff274d647b8a64719f60302f53cb021d2d88c1f1/src/ffmpegio/probe.py#L451), when in reality it returns all that inside of a list. [Even the docstring has it right](https://github.com/python-ffmpegio/python-ffmpegio/blob/ff274d647b8a64719f60302f53cb021d2d88c1f1/src/ffmpegio/probe.py#L472-L473). It's purely an issue with the type hint.

**Comment by tikuma-lsuhsc** [comment]
@JadeJuno - Thanks for spotting the typo. What you reported as well as several other typehint errors have been fixed on the main branch.

I'm currently in a slow process of putting in type hints across the package, and I messed this one up. If you see any other errors, please do report. I have a lot to go through here.
