### ISSUE TITLE
`nb_samples` not contained in ffmpegio.probe.full_details(file,select_streams=0)

### ISSUE THREAD

**Issue by julienlargetpiet** [python-ffmpegio/python-ffmpegio#52]
I have an mp3 file named `g.mp3`, and want full details on it.

So i use the following code:

<code>import ffmpegio </code>
<br/>

<code> from pprint import pprint </code>

<br/>

<code>pprint(ffmpegio.probe.full_details('g.mp3', select_streams=0))</code>

Returns:

<code/>
{'format': {'bit_rate': 128409,
            'duration': 6.624,
            'filename': 'g.mp3',
            'format_long_name': 'MP2/3 (MPEG audio layer 2/3)',
            'format_name': 'mp3',
            'nb_programs': 0,
            'nb_stream_groups': 0,
            'nb_streams': 1,
            'probe_score': 51,
            'size': 106323,
            'start_time': 0.023021,
            'tags': {'compatible_brands': 'isomiso2avc1mp41',
                     'encoder': 'Lavf61.1.100',
                     'major_brand': 'isom',
                     'minor_version': 512}},
 'programs': [],
 'stream_groups': [],
 'streams': [{'avg_frame_rate': '0/0',
              'bit_rate': 128000,
              'bits_per_sample': 0,
              'channel_layout': 'stereo',
              'channels': 2,
              'codec_long_name': 'MP3 (MPEG audio layer 3)',
              'codec_name': 'mp3',
              'codec_tag': '0x0000',
              'codec_tag_string': '[0][0][0][0]',
              'codec_type': 'audio',
              'disposition': {'attached_pic': 0,
                              'captions': 0,
                              'clean_effects': 0,
                              'comment': 0,
                              'default': 0,
                              'dependent': 0,
                              'descriptions': 0,
                              'dub': 0,
                              'forced': 0,
                              'hearing_impaired': 0,
                              'karaoke': 0,
                              'lyrics': 0,
                              'metadata': 0,
                              'non_diegetic': 0,
                              'original': 0,
                              'still_image': 0,
                              'timed_thumbnails': 0,
                              'visual_impaired': 0},
              'duration': 6.624,
              'duration_ts': 93477888,
              'index': 0,
              'initial_padding': 0,
              'r_frame_rate': '0/0',
              'sample_fmt': 'fltp',
              'sample_rate': 48000,
              'start_pts': 324870,
              'start_time': 0.023021,
              'tags': {'encoder': 'Lavc61.3.'},
              'time_base': Fraction(1, 14112000)}]}

</code>
<br/>

But i do not see any `nb_samples` key.

I also report this issue because @hokiedsp told me to do so here:

https://stackoverflow.com/questions/79019186/why-the-number-of-samples-given-by-ffmpegio-differs-using-2-methods

**Comment by tikuma-lsuhsc** [comment]
@julienlargetpiet - Thanks for reporting (hokiedsp is my "private" handle FYI).

As I anticipated, you have the `start_time` stream attribute, which has not been taken into consideration of computation of nb_samples. However, the numbers do not match what you were showing on SO.

You have `sample_rate = 48000` and `time_base = 1/14112000`, this means every sample consumes 294 ticks. With `duration_ts = 93477888` I expect you have `duration_ts / 294 = 317952` samples total, which should be what `audio_streams_basic()` reports as `nb_samples` if it is not given by ffprobe. But this is different from what you originally reported, which was `292608`. Maybe you are using a different file?

Let me go on with the math. The stream starts at `start_pts = 324870`. In other words, it skips the first `start_pts/294 = 1105` samples. So, I suspect with this particular file, `audio.read()` returns `317952 - 1105 = 316847` samples. Could you verify this?

**Comment by julienlargetpiet** [comment]
Tanks, yes i tried the command on a different file on SO, which was on 44100. 

Now for this file `g.mp3`:

`ffmpegio.audio.read('g.mp3')[1].shape[0]`

Returns

`316416`

So with `317952 - start_pts/124` we are closer to `316416` but still 431 difference.

I'm not an audio expert, what is the unit of `start_pts` ?

**Comment by julienlargetpiet** [comment]
If its possible to have `end_pts`, 
so is it possible that the file skips the end at a value of pts that would solve the following equation:

`end_pts / 124 = 431`

?

**Comment by tikuma-lsuhsc** [comment]
Hmmm, interesting... I'm afraid there isn't much I can do about this as what you got is all made available by ffprobe.

>I'm not an audio expert, what is the unit of start_pts ?

`pts` stands for presentation time stamp and any attribute ends with it (`start_pts`, `duration_pts`, etc.) is a count of the number of timebase ticks. In the op example, 1 tick = 1/14112000 seconds. `pts` gives us more accurate results than relying on a floating-point "seconds" counterparts like `start_time` and `duration` which ffprobe only print 3 significant digits.

**Comment by tikuma-lsuhsc** [comment]
> If its possible to have `end_pts`, so is it possible that the file skips the end at a value of pts that would solve the following equation:
> 
> `end_pts / 124 = 431`
> 
> ?

No, the attributes listed by `full_details()` is exactly that: Everything that ffprobe spits out.

**Comment by julienlargetpiet** [comment]
Ok, thanks for helping me and explaining me what `pts` is.

If i have news, i will post here.

**Comment by tikuma-lsuhsc** [comment]
What is your goal for needing the sample count ahead of time? For audio files, it's often fast enough to just decode and check with modern computing resources.

**Comment by julienlargetpiet** [comment]
I was working on an algorithm capable of extracting voices and eliminate all type of interfering noises in audio files, so i had to be as precise as possible on the timestamps.

**Comment by tikuma-lsuhsc** [comment]
If that's the case, MP3 is a fixed sampling rate format (as most if not all audio encoding formats are) so you only need the sampling rate to ensure the timestamps (relative to the first sample of the file).

In other words, this is what I usually do myself:

```python
import numpy as np
import ffmpegio as ff

file = 'audio.mp3'
fs, x = ff.audio.read(file,sample_fmt='dbl') # x is always a 2D array with time axis being the first dimension
t = np.arange(x.shape[0])/fs # time vector in seconds
```

**Comment by julienlargetpiet** [comment]
Interesting, but i here is the code that just took the blocks number that were associated to a higher value of the low limit, before dealing with interfering noises.

<code>

with ffmpegio.open(file, 'ra', blocksize = nsamples, sample_fmt = 'dbl') as file_opened:
        over_val = False
        for i, indata in enumerate(file_opened):
            volume_norm = np.linalg.norm(indata) * 10
            cur_lst2.append(volume_norm)
            if volume_norm > base_volume:
                cur_lst.append(i)
                over_val = True
            elif over_val:
                cur_lst.append("end")
                over_val = False

</code>

I hope not to be confusing, but the architecture of my algo is the following:

- take the blocks number that are associated to a higher value of decibel than the low limit
- filter the sound drops and sound pops 

Because interfering noises are flagged according to their intensity, i need to take in count all number blocks that are higher of the low limit.

**Comment by tikuma-lsuhsc** [comment]
Ah, so your algorithm is frame-based. My rule-of-thumb is to separate data I/O and data processing as much as possible. So, I'd do something like this instead:

```python
file = 'audio.mp3'
nsamples = 16 # block size

fs, x = ff.audio.read(file,sample_fmt='dbl') # x is always a 2D array with time axis being the first dimension
nb_samples = x.shape[0]
nb_blocks = nb_samples//nsamples #truncates the last block with less than < nsamples, make adjustment if you need them

X = x[:nb_blocks*nb_samples,0].reshape(nb_blocks, nb_samples)

over_val = False
for i, indata in enumerate(X):
    volume_norm = np.linalg.norm(indata) * 10
    cur_lst2.append(volume_norm)
    if volume_norm > base_volume:
        cur_lst.append(i)
        over_val = True
    elif over_val:
        cur_lst.append("end")
        over_val = False
```

**Comment by julienlargetpiet** [comment]
I see, 

But, why it is not recommended to filter the blocks number on the fly? 
It appears faster.

Here the full algo to make it clearer:

```{python3}

import ffmpegio
import numpy as np
import os 
import glob as glob
import csv
import re
import sys

all_files = sys.argv[1:]
nsamples = 16 
base_volume = 1
min_duration = 0.15
min_cut_duration = 0.14

for file in all_files:

    cur_csv = file[0:(len(file) - 3)] + "csv"
    cur_csv = open(cur_csv, "w")
    cur_csv = csv.writer(cur_csv, delimiter = ",", lineterminator = "\n")
   
    for i in os.listdir("cur_split"): os.remove(f"cur_split/{i}")

    duration = float(ffmpegio.probe.audio_streams_basic(file)[0]['duration']) / ffmpegio.audio.read(file)[1].shape[0] * nsamples

    timestamps_lst = [["start", "end"]]
    cur_lst = []
    with ffmpegio.open(file, 'ra', blocksize = nsamples, sample_fmt = 'dbl') as file_opened:
        over_val = False
        for i, indata in enumerate(file_opened):
            volume_norm = np.linalg.norm(indata) * 10
            if volume_norm > base_volume:
                cur_lst.append(i)
                over_val = True
            elif over_val:
                cur_lst.append("end")
                over_val = False

    v_strt = cur_lst[0] 
    v_end = v_strt
    v_af = 0

    for i in range(0, len(cur_lst)):
        if cur_lst[i] == "end":
            if i + 1 < len(cur_lst):
                if (cur_lst[i + 1] - cur_lst[i - 1]) * duration > min_cut_duration:
                    cur_duration = (cur_lst[i - 1] - v_strt) * duration 
                    if cur_duration > min_duration:
                        v_end = cur_lst[i - 1] * duration
                        if v_strt - 1 > 0:
                            v_strt -= 1
                        v_strt *= duration
                        os.system(f'ffmpeg -i {file} -acodec copy -ss {v_strt} -to {v_end} cur_split/{v_af}.mp3')
                        timestamps_lst.append([v_strt, v_end])
                        if i + 1 < len(cur_lst):
                            v_strt = cur_lst[i + 1] 
                            v_af += 1
            else:
                cur_duration = (cur_lst[i - 1] - v_strt) * duration 
                if cur_duration > min_duration:
                    v_end = cur_lst[i - 1] * duration
                    if v_strt - 1 > 0:
                        v_strt -= 1
                    v_strt *= duration
                    os.system(f'ffmpeg -i {file} -acodec copy -ss {v_strt} -to {v_end} cur_split/{v_af}.mp3')
                    timestamps_lst.append([v_strt, v_end])
                    if i + 1 < len(cur_lst):
                        v_strt = cur_lst[i + 1] 
                        v_af += 1

    cur_csv.writerows(timestamps_lst)
    cur_glob = []
    for i in range(0, len(glob.glob("cur_split/*.mp3"))): cur_glob.append(f"file 'cur_split/{i}.mp3'")
    cur_files = open("cur_files.txt", "w")
    cur_files.write("\n".join(cur_glob))
    cur_files.close()

    os.system(f"ffmpeg -f concat -i cur_files.txt -acodec copy output_dir/{file}")

```

**Comment by tikuma-lsuhsc** [comment]
> But, why it is not recommended to filter the blocks number on the fly?
> It appears faster.

Interesting. If it's faster, then it trumps what I said :)

That being said, the only reason that I can think of is your actual MP3 file is really long (hours) and fills up your RAM... Oh wait, I see. You're running MP3 decoding and your main processing concurrently with the stream approach. This must be why it's faster as you don't need to wait for the decoding to be done. Well, keep it as is. 

That being said, it may be better for you to read all samples first into the 2D array `X` as I have it above may save you more time as doing so you can eliminate **all** the subsequent `os.system` calls except for the last one. You just want to keep the frames with sufficiently high volumes, right?

Assuming that's the extent, something like this should do it much faster:

```python
X = x[:nb_blocks*nb_samples,0].reshape(nb_blocks, nb_samples) # assuming mono

volume_norm = np.linalg.norm(X,axis=0)
keep = volume_norm > base_volume
xout = X[keep].reshape(-1)
ffmpegio.audio.write(f'output_dir/{file}', xout, fs)
```

**Comment by julienlargetpiet** [comment]
Great, i will test that!

**Comment by tikuma-lsuhsc** [comment]
As for the duration bug, there is a known bug in FFmpeg reporting incorrect mp3 duration. See [this ticket](https://trac.ffmpeg.org/ticket/10163). I'm deferring to resolve this issue until the bug is fixed (so I know how to handle the start time correctly).

There are two separate issues that I spotted. 1: FFmpeg/FFprobe underreports the duration  and 2: FFmpeg decodes extra samples at the end.

**Comment by julienlargetpiet** [comment]
Ok tanks for letting me know that.

**Comment by julienlargetpiet** [comment]
> > But, why it is not recommended to filter the blocks number on the fly?
> > It appears faster.
> 
> Interesting. If it's faster, then it trumps what I said :)
> 
> That being said, the only reason that I can think of is your actual MP3 file is really long (hours) and fills up your RAM... Oh wait, I see. You're running MP3 decoding and your main processing concurrently with the stream approach. This must be why it's faster as you don't need to wait for the decoding to be done. Well, keep it as is.
> 
> Now, looking at the rest of your code, it could very well run faster overall to read all samples first into the 2D array `X` as I have it above as doing so you can eliminate **all** the subsequent `os.system` FFmpeg calls except for the last one. Remember writing to a disk is expensive.
> 
> You just want to keep the frames with sufficiently high volumes, right? Assuming that's the extent (I only skimmed your code quickly), something like this should do it much faster:
> 
> ```python
> X = x[:nb_blocks*nb_samples,0].reshape(nb_blocks, nb_samples) # assuming mono
> 
> volume_norm = np.linalg.norm(X,axis=0)
> keep = volume_norm > base_volume
> xout = X[keep].reshape(-1)
> ffmpegio.audio.write(f'output_dir/{file}', xout, fs)
> ```

First, why x[:nb_blocks* nb_samples, 0] if len(x) = nb_samples ?

Maybe you mean:

x[:nb_blocks * nsamples, 0] ?

because nsamples = 16

and nsamples * nb_blocks = len(x)

**Comment by tikuma-lsuhsc** [comment]
Yes, it should be `nsamples`, it was a typo. 

>Also the os.system are called for 2 reasons.

Yep. That's how I read it. As I said, they're unnecessary disk access & decodes. But, if speed is non-issue for you, I'm glad things got sorted out!
